fix(freecad): update release name regex
chocolatey/chocolatey-coreteampackages pull request #2578
Opened 2024-11-22 16:57 UTC by Rotzbua

## Description

Match new names with v1:

- FreeCAD_1.0.0-conda-Windows-x86_64-installer-1.exe
- FreeCAD_1.0.0-conda-Windows-x86_64-py311.7z

## Motivation and Context

Missing update to v1.

## How Has this Been Tested?

Regex tester.

## Screenshot (if appropriate, usually isn't needed):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

## Original Location

Release v1:
https://github.com/FreeCAD/FreeCAD/releases/tag/1.0.0

2024-12-02 17:40 UTC, luzpaz commented
Does this need a 'Needs Review' label ?

2024-12-14 22:24 UTC, mkosmo commented
What's it going to take to get this merged?

2024-12-21 19:55 UTC, TheCakeIsNaOH requested changes
As per the PR template, please test the updated package in the Chocolatey test environment.

2024-12-21 19:55 UTC, TheCakeIsNaOH commented on automatic/freecad/update_helper.ps1
> -      $mobile = "portable"
As per https://github.com/chocolatey-community/chocolatey-packages/pull/2403#discussion_r1498488093
@RedBaron2 suggested that the `$mobile` variables be kept in use.

2024-12-27 10:16 UTC, luzpaz commented
soft bump

2025-03-10 09:58 UTC, elipsion commented
Bump, @Rotzbua

2025-03-24 17:04 UTC, regexaurus commented
@Rotzbua would you please take a look at and approve the change to your PR requested by @TheCakeIsNaOH?
Hopefully that will move things along with your PR being accepted. Thank you!

2025-05-06 23:35 UTC, pauby commented on automatic/freecad/update_helper.ps1
> -      $mobile = "portable"
To get this over the line, is that all that needs to be added back here? Are the rest of the changes good?

If that is all we are waiting on, I'm happy to make that change. If there is more, I propose we close this PR unless somebody else wants to pick it up.

2025-05-07 00:55 UTC, TheCakeIsNaOH commented on automatic/freecad/update_helper.ps1
> -      $mobile = "portable"
The other code looked good to me, this was the only change.
This PR also would need to be tested in the test environment, as per unchecked box in the PR body.

2025-05-07 02:53 UTC, luzpaz commented
@Rotzbua ?

2025-05-07 11:30 UTC, closed without merging